### ISSUE TITLE
Multiple WITH DOCKER --load fails on 0.6.3

### ISSUE THREAD

**Issue by ingwarsw** [earthly/earthly#1582]
Multiple `WITH DOCKER --load`  is broken in `0.6.3`
```
regression-image-test:
    FROM alpine
    # Without SAVE IMAGE works
    SAVE IMAGE regression/tests

# Without COMMAND works
RUN_ONE_REG:
    COMMAND
    WITH DOCKER --load regression/test=+regression-image-test
        RUN echo works 1
    END

regression-test:
    FROM earthly/dind:alpine
    # Command needs to be invoked with 2 different args (they dont need to be even used)
    DO +RUN_ONE_REG --ANY_ARG=1
    DO +RUN_ONE_REG

```
It worked in 0.6.2 but now it gets
```
Error: build target: build main: bkClient.Build: failed to solve: image kentik/liquidbase is defined multiple times for the same default platform
```

`earthly config global.conversion_parallelism 0` is not helping

**Comment by alexcb** [comment]
We just released v0.6.4 which fixes this; thanks for reporting it.

**Comment by ingwarsw** [comment]
@alexcb Issue is still there..
```
Error stack trace:
github.com/moby/buildkit/util/stack.Enable
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/util/stack/stack.go:77
github.com/moby/buildkit/util/grpcerrors.FromGRPC
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/util/grpcerrors/grpcerrors.go:188
github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/util/grpcerrors/intercept.go:41
google.golang.org/grpc.(*ClientConn).Invoke
        google.golang.org/grpc@v1.42.0/call.go:35
github.com/moby/buildkit/api/services/control.(*controlClient).Solve
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/api/services/control/control.pb.go:1434
github.com/moby/buildkit/client.(*Client).solve.func2
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/client/solve.go:219
golang.org/x/sync/errgroup.(*Group).Go.func1
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
        runtime/asm_arm64.s:1133
Error: build target: build main: bkClient.Build: failed to solve: image my/image:test is defined multiple times for the same default platform
```
```
earthly version v0.6.4 darwin/arm64; macOS
```

Tested with `global.conversion_parallelism: 0` and without..

**Comment by alexcb** [comment]
This is only happening with `VERSION 0.5` functionality; i.e.

```
VERSION 0.5

regression-image-test:
    FROM alpine
    # Without SAVE IMAGE works
    SAVE IMAGE regression/tests

# Without COMMAND works
RUN_ONE_REG:
    COMMAND
    WITH DOCKER --load regression/test=+regression-image-test
        RUN echo works 1
    END

regression-test:
    FROM earthly/dind:alpine
    # Command needs to be invoked with 2 different args (they dont need to be even used)
    DO +RUN_ONE_REG --ANY_ARG=1
    DO +RUN_ONE_REG
```

If it's possible to use `VERSION 0.6` the problem no longer occurs.

**Comment by vladaionescu** [comment]
Thanks for the repro script @ingwarsw! Highly useful. This is now fixed and it will be out in the next release.
