### ISSUE TITLE
Inconsistent graph state error when running on a shared buildkit instance

### ISSUE THREAD

**Issue by brandonSc** [earthly/earthly#2454]
A user is reporting the following error, when running CI on a local, but re-used shared buildkit instance:
```
Error: build target: build main: failed to solve: failed to get edge: inconsistent graph state
```

The error is intermittent and usually works after a re-run. They are not using shared cache flags, due to previous suggestions we gave them. 

See here for context: https://earthlycommunity.slack.com/archives/C01DL2928RM/p1669293808712079

Note I remember running into this error frequently when we first started developing satellites several months ago, but a combination of fixes and removal of shared cache flags resolved it (IIRC).

Possibly related issue: https://github.com/earthly/earthly/issues/2957

EDIT: Since this issue is a top priority for us we will be providing weekly updates on our progress in #2957.

**Comment by FelixDQ** [comment]
Some more notes about our setup:
* The error seems to happen when the server is under heavy load. I have only seen the error in runs where the message `Warning: Currently under heavy load. Performance will be affected` appears. 
* I can confirm that we still see the error in the latest earthly version (`v0.6.30`).
* We are running a monorepo with a root Earthfile similar to the setup described in [this blog post](https://earthly.dev/blog/golang-monorepo/), but with around ~40 projects/libs. Some of the projects are probably being starved of resources during the build process due to other builds being run in parallel.

**Comment by jazzdan** [comment]
This started happening to us today too.

**Comment by jazzdan** [comment]
This has happened to us kinda regularly, about once every 1-2 weeks over the last couple of months.

**Comment by FelixDQ** [comment]
As a workaround, we have reduced the frequency of the errors by doing the following:
* Disable build parallelism. We now only run one earthly command at a time. This reduced the frequency of the errors by a lot, but is a bit annoying if the build queue is long.
* We have a cronjob stopping the buildkit container and running `earthly bootstrap` again every night. I'm not 100% sure if this affect this specific error, but it seems to stop the `Warning: Currently under heavy load. Performance will be affected` from appearing.

The error still happens every now and then, but much less frequently than before.

**Comment by sdaschner** [comment]
Also happens to us (using `earthly version v0.7.5 0857e35cefb1a0155638f47b3ac0558844b48c3f linux/amd64; Arch Linux`).

I'm actually running a single `earthly` command, but the projects includes a quite big graph (around 500-1000 targets with all nested permutations). Thinking about splitting that up in individual invocations for the time being.

Any updates or roadmap on this issue? @alexcb

**Comment by alexcb** [comment]
> Any updates or roadmap on this issue? @alexcb

We've been working through some data race warnings, which are documented under https://github.com/earthly/earthly/issues/2957#issuecomment-1625808777

We'll be posting more updates under #2957 as we make progress.

**Comment by alexcb** [comment]
#2957 has been fixed as of of [v0.7.21](https://github.com/earthly/earthly/releases/tag/v0.7.21); that issue was a race condition inside the buildkit scheduler, in particular when merging (deduplicating) multiple edges within the build graph. I _think_ this issue is related, but triggered a different error message. I'm going to close this as fixed, but if it happens again please reopen this.

**Comment by madsnedergaard** [comment]
It's seems like we're still having this problem despite updating to v0.7.21 and using the feature flag 😬 
https://cloud.earthly.dev/builds/b7cf3efd-3c04-41e9-938c-615e2c8876d2

<img width="1187" alt="Screenshot 2023-10-30 at 15 02 32" src="https://github.com/earthly/earthly/assets/3296643/affc4a12-c20e-48cb-98d8-d4170a2a057c">

<img width="850" alt="Screenshot 2023-10-30 at 15 02 19" src="https://github.com/earthly/earthly/assets/3296643/e6b06421-9411-4025-8b4e-33e8f9cbcbd9">

<img width="550" alt="Screenshot 2023-10-30 at 15 04 01" src="https://github.com/earthly/earthly/assets/3296643/8516d5b0-697b-4e4a-b553-d4fea57ab7e3">

**Comment by alexcb** [comment]
@madsnedergaard can you confirm that your remote buildkit instance (or satellite) has also been updated to v0.7.21?

If so, any sort of reproduction case for this would be incredibly helpful.

**Comment by alexcb** [comment]
We've hear from a second user, who confirmed their satellite was indeed on v0.7.21; we'll reopen this as it doesn't seem related to the scheduler error.

again, if anyone comes up with a reproduction for this, please do share :pleading_face:

**Comment by madsnedergaard** [comment]
So sorry for reopening this topic, I was so happy on your behalf that it was finally done 😔

> @madsnedergaard can you confirm that your remote buildkit instance (or satellite) has also been updated to v0.7.21?

Yes, our CI server is running `v0.7.21`.

<img width="1004" alt="Screenshot 2023-10-30 at 20 54 32" src="https://github.com/earthly/earthly/assets/3296643/ab599284-f9c2-493f-b3e1-ac358711b158">


> If so, any sort of reproduction case for this would be incredibly helpful.

We unfortunately also can't really figure out why it happens or reproduce it, but if it happens again frequently we'll spend some time attempting to create a reliable setup for triggering it!

**Comment by ingwarsw** [comment]
We have also encountered it..
I trier rebuilding failed job and I got same error 3 times in a row (I run it 4th time with --no-cache and it started)

Remote builkit
```
00:00:27.005             buildkitd | Connecting to tcp://buildkitd-earthly-buildkit-chart.jenkins.svc.cluster.local:8372...
00:00:28.374             buildkitd | Version github.com/earthly/buildkit v0.7.21 0b107b045b571b4f3184d6d975e567bd46d213bd
00:00:28.374             buildkitd | Platforms: linux/amd64 (native) linux/amd64/v2 linux/amd64/v3 linux/amd64/v4 linux/386
00:00:28.374             buildkitd | Utilization: 0 other builds, 0/20 op load
00:00:28.374             buildkitd | GC stats: 419 GB cache, avg GC duration 245ms, all-time GC duration 21m55.763s, last GC duration 0s, last cleared 0 B
```

Client version
```
 earthly version v0.7.20 9600f376026c11d23eb43fc68ad716d6ae4cca2e linux/amd64; Debian GNU/Linux 11 (bullseye)
```

Error
```
build target: build main: failed to solve: async force execution for +kbt-prepare: unlazy force execution: failed to get edge: inconsistent graph state
```

**Comment by jazzdan** [comment]
Just chiming in to say this is still happening to us as well on our `v0.7.21` satellites:

```
earthly satellites ls
   NAME       PLATFORM     SIZE    VERSION  STATE
   ci         linux/amd64  xlarge  v0.7.21  operational
*  cloud-dev  linux/amd64  xlarge  v0.7.21  operational
```

**Comment by immesys** [comment]
I'm getting this even with a local build with v0.7.21. It happens to me about 25% of the time, so is very reproducible.

**Comment by alexcb** [comment]
Our ideal reproduction case would involve a clear initial cache, i.e. `earthly prune --reset`, followed by running earthly against one (or more) Earthfile targets.

**Comment by mitre-tm** [comment]
I am chiming in to say this is still happening on our v0.7.22 satellite as well:
```
Error: build target: build main: failed to solve: async force execution for ./curated-shifts+test-unit: unlazy force execution: process "/bin/sh -c DIND_COMMIT=42b1175eda071c0e9121e1d64345928384a93df1 DOCKER_TLS_CERTDIR=/certs DOCKER_VERSION=20.10.14 PATH=/bin/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c 'npm run test:unit'" did not complete successfully: exit code: 1
View logs at https://cloud.earthly.dev/builds/60011bf0-41b0-4d65-b9f0-5dfc8b370b66
```

PS: If the above is not related to the same issue, please point me to the correct one (here is the [search](https://github.com/earthly/earthly/issues?q=is%3Aissue+%22failed+to+solve%3A+async+force+execution%22) I did)

**Comment by flemzord** [comment]
We also have this error very often in Earthly. 
It's really tiring.

**Comment by alexcb** [comment]
This is the first time I got this error since adding 5f287a248e3bc1421048626c278eabc5e4f0f49f

I ran `~/gh/earthly/earthly/ast/tests$ earthly +update-all` while dealing with a unrelated change where I was renaming `smoke.earth` to `parser-smoke.earth` -- could it be that this bug is related to renaming files?

Here's the full buildkit logs:
[buildkit-log-2023-12-15.txt](https://github.com/earthly/earthly/files/13689591/buildkit-log-2023-12-15.txt)

**Comment by FelixDQ** [comment]
There doesn't seem to be a correlation between renaming and the failures on our CI 😕 . In the last 30 days, we've seen `inconsistent graph state` 14 times. Of those:
* 10 builds only had modified files in the commit
* 1 build had deleted files in the commit
* 3 builds had added files in the commit
* 0 builds had file renames.

Note that these numbers only look at the commit for which the build was run. I don't know the cache state before, so if some of these were on old branches with an outdated cache, there might've been renamed files in the meantime.

**Comment by alexcb** [comment]
We got a sample which includes the initial call to `loadUnlocked-add`, followed by it being `delete`ed, then followed by the final `get-edge-not-found` error:

```
sha256:7f718cfe4d99b2d0c36d11be9c3d15765002a53c9497934f3c1cbf5181495347 name=copy /code/some/path/here /some-dst-path desiredState=complete
num items in active history: 1755

sha256:7f718cfe4d99b2d0c36d11be9c3d15765002a53c9497934f3c1cbf5181495347 get-edge-not-found 2023-12-19 13:55:54.560990333 +0000 UTC m=+1674.819538246
sha256:7f718cfe4d99b2d0c36d11be9c3d15765002a53c9497934f3c1cbf5181495347 delete 2023-12-19 13:55:54.427094091 +0000 UTC m=+1674.685641900
sha256:7f718cfe4d99b2d0c36d11be9c3d15765002a53c9497934f3c1cbf5181495347 loadUnlocked-add 2023-12-19 13:55:54.302671359 +0000 UTC m=+1674.561219185
sha256:7f718cfe4d99b2d0c36d11be9c3d15765002a53c9497934f3c1cbf5181495347 loadUnlocked-not-found-dgstWithoutCache 2023-12-19 13:55:54.302668556 +0000 UTC m=+1674.561216385
```

We had a number of other samples where the dumped "actives map history" was truncated, but of all captured instances, they've been related to a `COPY` or `SAVE ARTIFACT` being evaluated.

**Comment by alexcb** [comment]
in case anyone wants to follow along with parsing the active maps log messages, here's a very rudimentary parser:

```
#!/usr/bin/env python3

import sys

def get_after_str(s, substr):
    i = s.find(substr)
    if i < 0:
        raise ValueError("prefix not found")
    return s[i+len(substr):]

def parse_edge_history_item(s):
    dgst, event, date = s.split(' ', 2)
    return dgst, event, date

def parse(line):
    line = get_after_str(line, 'failed to get edge dgst=')
    header = line.split(';')[0]
    print(header)

    edge_history = [x.strip() for x in get_after_str(line, 'actives history: ').split(';')]

    missing_dgst, event, missing_date = parse_edge_history_item(edge_history[0])
    assert event == 'get-edge-not-found'

    print(f'num items in active history: {len(edge_history)}')

    try:
        for x in edge_history:
            dgst, event, date = parse_edge_history_item(x)
            if dgst == missing_dgst:
                print(x)
    except ValueError:
        print('truncated log line')


for line in sys.stdin:
    if line.endswith('\n'):
        line = line[:-1]
    parse(line)
```

**Comment by alexcb** [comment]
I came up with a reproduction for this why trying to update buildkit: https://github.com/earthly/earthly/issues/3825#issuecomment-1957683083

**Comment by travis-infosec** [comment]
I seem to get this when I call the second target but not the first in this erroneous setup:

```
ARG --global PROJ = $NAME
ARG --global TLD = "/usr/src/$NAME"

...

tool:
    COPY --dir +src/$PROJ $TLD
    RUN  # ... install tool
    RUN tool $TLD || true

analysis-tool:
    BUILD +tool
```

So if PROJ=x, and TLD=/usr/src/x
That first line of the tool target inadvertently winds up making a /usr/src/x/x
I've noticed a strange propensity for subsequent COPY commands to wind up in that nested directory, as if it changed the pwd to make the copy, and then earthly wasn't able to change it back before the subsequent COPY command ran, which strongly suggests to me a race condition in the "COPY --dir" code.

**Comment by alexcb** [comment]
We are currently investigating a modification to the buildkit scheduler (codename: ticktock, you know, like a clock ... and scheduler), as of earthly v0.8.12 this _highly experimental_ modification can be enabled, when running earthly locally, with `earthly --ticktock +your-target`.

**Comment by c0va23** [comment]
> We are currently investigating a modification to the buildkit scheduler (codename: ticktock, you know, like a clock ... and scheduler), as of earthly v0.8.12 this _highly experimental_ modification can be enabled, when running earthly locally, with `earthly --ticktock +your-target`.

I tested "ticktock" feature on our CI for a few hours. It looks like "inconsistent graph state" issue is fixed.

But it doesn't work when many earthly clients in parallel execute builds on one buildkit daemon. We were faced with two types of issues:
1. Layer caching partially doesn't work. For example, we have one CI job that sequentially executes tests and linters on all library projects. All library projects have one base target. After switching to "ticktock" buildkit, the build of every library project has been triggered to rebuild the base target from one of COPY commands (always same).
2. We faced with one linter and one compilation issue that was added and isn't fixed yet in one branch but was reported in the workflow run on another branch at the same time.

**Comment by alexcb** [comment]
@c0va23 thanks for the feedback, can you try again using https://github.com/earthly/earthly/releases/tag/v0.8.13

**Comment by c0va23** [comment]
> @c0va23 thanks for the feedback, can you try again using https://github.com/earthly/earthly/releases/tag/v0.8.13

I tried v0.8.13 with one buildkitd-ticktock to one earthly client to avoid my second issue. But issue with caching is actual.

**Comment by DbCrWk** [comment]
Hi y'all, we're also getting this issue:

```
Build error:unlazy force execution: failed to get edge: inconsistent graph state
```

We're running on a self-hosted satellite on EC2, which was working until today. Now, all of our builds run into this issue. We're not sure what's happening. Is there helpful information/context I can provide to reproduce?
